 const Options = [ {label:"Allerdale Borough Council", value:"Allerdale_Borough_Council"},
 {label:"Arun District Council", value:"Arun_District_Council"},
 {label:"Ashfield District Council", value:"Ashfield_District_Council"},
 {label:"Barnsley Metropolitan Borough Council", value:"Barnsley_Metropolitan_Borough_Council"},
 {label:"Basildon Borough Council", value:"Basildon_Borough_Council"},
 {label:"Bassetlaw District Council", value:"Bassetlaw_District_Council"},
 {label:"Bath and North East Somerset Council", value:"Bath_and_North_East_Somerset_Council"},
 {label:"Bedford Borough Council", value:"Bedford_Borough_Council"},
 {label:"Birmingham City Council", value:"Birmingham_City_Council"},
 {label:"Blaby District Council", value:"Blaby_District_Council"},
 {label:"Blackburn with Darwen Borough Council", value:"Blackburn_with_Darwen_Borough_Council"},
 {label:"Blackpool Borough Council", value:"Blackpool_Borough_Council"},
 {label:"Bolton Metropolitan Borough Council", value:"Bolton_Metropolitan_Borough_Council"},
 {label:"Borough Council of King's Lynn and West Norfolk", value:"Borough_Council_of_King's_Lynn_and_West_Norfolk"},
 {label:"Boston Borough Council", value:"Boston_Borough_Council"},
 {label:"Bracknell Forest Council", value:"Bracknell_Forest_Council"},
 {label:"Brentwood Borough Council", value:"Brentwood_Borough_Council"},
 {label:"Brighton and Hove City Council", value:"Brighton_and_Hove_City_Council"},
 {label:"Broadland District Council", value:"Broadland_District_Council"},
 {label:"Bromsgrove District Council", value:"Bromsgrove_District_Council"},
 {label:"Bury Metropolitan Borough Council", value:"Bury_Metropolitan_Borough_Council"},
 {label:"Cambridge City Council", value:"Cambridge_City_Council"},
 {label:"Cannock Chase District Council", value:"Cannock_Chase_District_Council"},
 {label:"Carlisle City Council", value:"Carlisle_City_Council"},
 {label:"Castle Point Borough Council", value:"Castle_Point_Borough_Council"},
 {label:"Charnwood Borough Council", value:"Charnwood_Borough_Council"},
 {label:"Cherwell District Council", value:"Cherwell_District_Council"},
 {label:"Cheshire East Council", value:"Cheshire_East_Council"},
 {label:"Cheshire West and Chester Council", value:"Cheshire_West_and_Chester_Council"},
 {label:"Chiltern District Council", value:"Chiltern_District_Council"},
 {label:"Chorley Borough Council", value:"Chorley_Borough_Council"},
 {label:"City of Lincoln Council", value:"City_of_Lincoln_Council"},
 {label:"City of London Corporation", value:"City_of_London_Corporation"},
 {label:"City of Westminster", value:"City_of_Westminster"},
 {label:"Colchester Borough Council", value:"Colchester_Borough_Council"},
 {label:"Copeland Borough Council", value:"Copeland_Borough_Council"},
 {label:"Corby Borough Council", value:"Corby_Borough_Council"},
 {label:"Craven District Council", value:"Craven_District_Council"},
 {label:"Crawley Borough Council", value:"Crawley_Borough_Council"},
 {label:"Dacorum Borough Council", value:"Dacorum_Borough_Council"},
 {label:"Darlington Borough Council", value:"Darlington_Borough_Council"},
 {label:"Dartmoor National Park Authority", value:"Dartmoor_National_Park_Authority"},
 {label:"Daventry District Council", value:"Daventry_District_Council"},
 {label:"Doncaster Metropolitan Borough Council", value:"Doncaster_Metropolitan_Borough_Council"},
 {label:"Dover District Council", value:"Dover_District_Council"},
 {label:"East Cambridgeshire District Council", value:"East_Cambridgeshire_District_Council"},
 {label:"East Devon District Council", value:"East_Devon_District_Council"},
 {label:"East Hertfordshire District Council", value:"East_Hertfordshire_District_Council"},
 {label:"East Lindsey District Council", value:"East_Lindsey_District_Council"},
 {label:"East Northamptonshire Council", value:"East_Northamptonshire_Council"},
 {label:"East Riding of Yorkshire Council", value:"East_Riding_of_Yorkshire_Council"},
 {label:"East Staffordshire Borough Council", value:"East_Staffordshire_Borough_Council"},
 {label:"Eastbourne Borough Council", value:"Eastbourne_Borough_Council"},
 {label:"Eastleigh Borough Council", value:"Eastleigh_Borough_Council"},
 {label:"Eden District Council", value:"Eden_District_Council"},
 {label:"Elmbridge Borough Council", value:"Elmbridge_Borough_Council"},
 {label:"Epping Forest District Council", value:"Epping_Forest_District_Council"},
 {label:"Epsom and Ewell Borough Council", value:"Epsom_and_Ewell_Borough_Council"},
 {label:"Exeter City Council", value:"Exeter_City_Council"},
 {label:"Fareham Borough Council", value:"Fareham_Borough_Council"},
 {label:"Fenland District Council", value:"Fenland_District_Council"},
 {label:"Forest of Dean District Council", value:"Forest_of_Dean_District_Council"},
 {label:"Fylde Borough Council", value:"Fylde_Borough_Council"},
 {label:"Gateshead Metropolitan Borough Council", value:"Gateshead_Metropolitan_Borough_Council"},
 {label:"Gosport Borough Council", value:"Gosport_Borough_Council"},
 {label:"Guildford Borough Council", value:"Guildford_Borough_Council"},
 {label:"Harborough District Council", value:"Harborough_District_Council"},
 {label:"Harlow District Council", value:"Harlow_District_Council"},
 {label:"Hartlepool Borough Council", value:"Hartlepool_Borough_Council"},
 {label:"Hastings Borough Council", value:"Hastings_Borough_Council"},
 {label:"Havant Borough Council", value:"Havant_Borough_Council"},
 {label:"Herefordshire Council", value:"Herefordshire_Council"},
 {label:"Hertsmere Borough Council", value:"Hertsmere_Borough_Council"},
 {label:"High Peak Borough Council", value:"High_Peak_Borough_Council"},
 {label:"Huntingdonshire District Council", value:"Huntingdonshire_District_Council"},
 {label:"Isle of Wight Council", value:"Isle_of_Wight_Council"},
 {label:"Isles of Scilly Council", value:"Isles_of_Scilly_Council"},
 {label:"Kettering Borough Council", value:"Kettering_Borough_Council"},
 {label:"Knowsley Metropolitan Borough Council", value:"Knowsley_Metropolitan_Borough_Council"},
 {label:"Lake District National Park Authority", value:"Lake_District_National_Park_Authority"},
 {label:"Leeds City Council", value:"Leeds_City_Council"},
 {label:"Leicester City Council", value:"Leicester_City_Council"},
 {label:"London Borough of Bexley", value:"London_Borough_of_Bexley"},
 {label:"London Borough of Brent", value:"London_Borough_of_Brent"},
 {label:"London Borough of Camden", value:"London_Borough_of_Camden"},
 {label:"London Borough of Croydon", value:"London_Borough_of_Croydon"},
 {label:"London Borough of Ealing", value:"London_Borough_of_Ealing"},
 {label:"London Borough of Enfield", value:"London_Borough_of_Enfield"},
 {label:"London Borough of Hammersmith & Fulham", value:"London_Borough_of_Hammersmith_&_Fulham"},
 {label:"London Borough of Haringey", value:"London_Borough_of_Haringey"},
 {label:"London Borough of Islington", value:"London_Borough_of_Islington"},
 {label:"London Borough of Lambeth", value:"London_Borough_of_Lambeth"},
 {label:"London Borough of Lewisham", value:"London_Borough_of_Lewisham"},
 {label:"London Borough of Merton", value:"London_Borough_of_Merton"},
 {label:"London Borough of Newham", value:"London_Borough_of_Newham"},
 {label:"London Borough of Richmond upon Thames", value:"London_Borough_of_Richmond_upon_Thames"},
 {label:"London Borough of Southwark", value:"London_Borough_of_Southwark"},
 {label:"London Borough of Tower Hamlets", value:"London_Borough_of_Tower_Hamlets"},
 {label:"London Borough of Wandsworth", value:"London_Borough_of_Wandsworth"},
 {label:"Luton Borough Council", value:"Luton_Borough_Council"},
 {label:"Manchester City Council", value:"Manchester_City_Council"},
 {label:"Mansfield District Council", value:"Mansfield_District_Council"},
 {label:"Melton Borough Council", value:"Melton_Borough_Council"},
 {label:"Mid Devon District Council", value:"Mid_Devon_District_Council"},
 {label:"Mid Sussex District Council", value:"Mid_Sussex_District_Council"},
 {label:"New Forest District Council", value:"New_Forest_District_Council"},
 {label:"New Forest National Park Authority", value:"New_Forest_National_Park_Authority"},
 {label:"Newcastle City Council", value:"Newcastle_City_Council"},
 {label:"North East Derbyshire District Council", value:"North_East_Derbyshire_District_Council"},
 {label:"North Hertfordshire District Council", value:"North_Hertfordshire_District_Council"},
 {label:"North Kesteven District Council", value:"North_Kesteven_District_Council"},
 {label:"North Lincolnshire Council", value:"North_Lincolnshire_Council"},
 {label:"North Norfolk District Council", value:"North_Norfolk_District_Council"},
 {label:"North Northamptonshire Council", value:"North_Northamptonshire_Council"},
 {label:"North Warwickshire Borough Council", value:"North_Warwickshire_Borough_Council"},
 {label:"North West Leicestershire District Council", value:"North_West_Leicestershire_District_Council"},
 {label:"Northampton Borough Council", value:"Northampton_Borough_Council"},
 {label:"Northumberland County Council", value:"Northumberland_County_Council"},
 {label:"Norwich City Council", value:"Norwich_City_Council"},
 {label:"Nuneaton and Bedworth Borough Council", value:"Nuneaton_and_Bedworth_Borough_Council"},
 {label:"Oadby and Wigston Borough Council", value:"Oadby_and_Wigston_Borough_Council"},
 {label:"Old Oak and Park Royal Development Corporation", value:"Old_Oak_and_Park_Royal_Development_Corporation"},
 {label:"Oldham Metropolitan Borough Council", value:"Oldham_Metropolitan_Borough_Council"},
 {label:"Portsmouth City Council", value:"Portsmouth_City_Council"},
 {label:"Preston City Council", value:"Preston_City_Council"},
 {label:"Redditch Borough Council", value:"Redditch_Borough_Council"},
 {label:"Reigate and Banstead Borough Council", value:"Reigate_and_Banstead_Borough_Council"},
 {label:"Ribble Valley Borough Council", value:"Ribble_Valley_Borough_Council"},
 {label:"Rochdale Metropolitan Borough Council", value:"Rochdale_Metropolitan_Borough_Council"},
 {label:"Rochford District Council", value:"Rochford_District_Council"},
 {label:"Rossendale Borough Council", value:"Rossendale_Borough_Council"},
 {label:"Royal Borough of Greenwich", value:"Royal_Borough_of_Greenwich"},
 {label:"Royal Borough of Kensington and Chelsea", value:"Royal_Borough_of_Kensington_and_Chelsea"},
 {label:"Royal Borough of Windsor and Maidenhead", value:"Royal_Borough_of_Windsor_and_Maidenhead"},
 {label:"Salford City Council", value:"Salford_City_Council"},
 {label:"Sevenoaks District Council", value:"Sevenoaks_District_Council"},
 {label:"Shropshire Council", value:"Shropshire_Council"},
 {label:"Solihull Metropolitan Borough Council", value:"Solihull_Metropolitan_Borough_Council"},
 {label:"South Bucks District Council", value:"South_Bucks_District_Council"},
 {label:"South Cambridgeshire District Council", value:"South_Cambridgeshire_District_Council"},
 {label:"South Downs National Park Authority", value:"South_Downs_National_Park_Authority"},
 {label:"South Gloucestershire Council", value:"South_Gloucestershire_Council"},
 {label:"South Holland District Council", value:"South_Holland_District_Council"},
 {label:"South Lakeland District Council", value:"South_Lakeland_District_Council"},
 {label:"South Norfolk District Council", value:"South_Norfolk_District_Council"},
 {label:"South Northamptonshire Council", value:"South_Northamptonshire_Council"},
 {label:"South Oxfordshire District Council", value:"South_Oxfordshire_District_Council"},
 {label:"South Ribble Borough Council", value:"South_Ribble_Borough_Council"},
 {label:"Southend-on-Sea Borough Council", value:"Southend-on-Sea_Borough_Council"},
 {label:"Spelthorne Borough Council", value:"Spelthorne_Borough_Council"},
 {label:"St Edmundsbury Borough Council", value:"St_Edmundsbury_Borough_Council"},
 {label:"St Helens Council", value:"St_Helens_Council"},
 {label:"Stafford Borough Council", value:"Stafford_Borough_Council"},
 {label:"Staffordshire Moorlands District Council", value:"Staffordshire_Moorlands_District_Council"},
 {label:"Stockport Metropolitan Borough Council", value:"Stockport_Metropolitan_Borough_Council"},
 {label:"Stratford-on-Avon District Council", value:"Stratford-on-Avon_District_Council"},
 {label:"Stroud District Council", value:"Stroud_District_Council"},
 {label:"Suffolk Coastal District Council", value:"Suffolk_Coastal_District_Council"},
 {label:"Sunderland City Council", value:"Sunderland_City_Council"},
 {label:"Swale Borough Council", value:"Swale_Borough_Council"},
 {label:"Swindon Borough Council", value:"Swindon_Borough_Council"},
 {label:"Tameside Metropolitan Borough Council", value:"Tameside_Metropolitan_Borough_Council"},
 {label:"Tamworth Borough Council", value:"Tamworth_Borough_Council"},
 {label:"Tandridge District Council", value:"Tandridge_District_Council"},
 {label:"Telford & Wrekin Council", value:"Telford_&_Wrekin_Council"},
 {label:"Tendring District Council", value:"Tendring_District_Council"},
 {label:"Test Valley Borough Council", value:"Test_Valley_Borough_Council"},
 {label:"Thanet District Council", value:"Thanet_District_Council"},
 {label:"Thurrock Council", value:"Thurrock_Council"},
 {label:"Trafford Metropolitan Borough Council", value:"Trafford_Metropolitan_Borough_Council"},
 {label:"Tunbridge Wells Borough Council", value:"Tunbridge_Wells_Borough_Council"},
 {label:"Warrington Borough Council", value:"Warrington_Borough_Council"},
 {label:"Warwick District Council", value:"Warwick_District_Council"},
 {label:"Watford Borough Council", value:"Watford_Borough_Council"},
 {label:"Waveney District Council", value:"Waveney_District_Council"},
 {label:"Wellingborough Borough Council", value:"Wellingborough_Borough_Council"},
 {label:"West Berkshire Council", value:"West_Berkshire_Council"},
 {label:"West Lancashire Borough Council", value:"West_Lancashire_Borough_Council"},
 {label:"West Lindsey District Council", value:"West_Lindsey_District_Council"},
 {label:"Wigan Metropolitan Borough Council", value:"Wigan_Metropolitan_Borough_Council"},
 {label:"Winchester City Council", value:"Winchester_City_Council"},
 {label:"Wirral Metropolitan Borough Council", value:"Wirral_Metropolitan_Borough_Council"},
 {label:"Woking Borough Council", value:"Woking_Borough_Council"},
 {label:"Worthing Borough Council", value:"Worthing_Borough_Council"},
 {label:"Wyre Borough Council", value:"Wyre_Borough_Council"},
 {label:"Wyre Forest District Council", value:"Wyre_Forest_District_Council"},
 {label:"Yorkshire Dales National Park Authority", value:"Yorkshire_Dales_National_Park_Authority"},
 ]

 export default Options;